# Generated by Django 2.1.2 on 2018-11-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('closet', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='Data de publicação')),
            ],
        ),
    ]
