# Generated by Django 2.1.2 on 2018-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_auto_20181121_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='Data de publicação'),
        ),
    ]
