# Generated by Django 2.1.2 on 2018-11-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_auto_20181121_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
